name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Lint (ruff)
        run: |
          python -m ruff check .
      - name: Type Check (mypy)
        run: |
          mypy pyfoamclone
      - name: Tests
        run: |
          pytest -q
