# -*- coding: utf-8 -*-
"""Lid .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NZBB51OouyvDUSJ7u3TdECNDrLGKHK8
"""



with open("/content/lid1.txt", 'r') as f:
  file_content = f.read()

print(file_content)

"""## Cell 1: Imports and Configuration"""

import numpy as np
from scipy.sparse import spdiags, csr_matrix
from scipy.sparse.linalg import bicgstab, cg
import matplotlib.pyplot as plt
import types

# All parameters are in one place for easy tweaking
config = {
    'grid': { 'Nx': 41, 'Ny': 41, 'Lx': 1.0, 'Ly': 1.0 },
    'physics': { 'rho': 1.0, 'mu': 0.01, 'U_lid': 1.0 }, # Re = 100
    'solver': { 'alpha_u': 0.7, 'alpha_p': 0.3, 'max_iter': 1000, 'tolerance': 1e-6 }
}

"""## Cell 2: Grid and Visualization Functions"""

def create_grid(cfg):
    grid = types.SimpleNamespace()
    grid.Nx, grid.Ny = cfg['Nx'], cfg['Ny']
    grid.Lx, grid.Ly = cfg['Lx'], cfg['Ly']
    grid.dx, grid.dy = grid.Lx / (grid.Nx - 1), grid.Ly / (grid.Ny - 1)
    grid.n_cells_x, grid.n_cells_y = grid.Nx - 1, grid.Ny - 1
    grid.total_cells = grid.n_cells_x * grid.n_cells_y
    grid.x_cc = np.linspace(grid.dx / 2, grid.Lx - grid.dx / 2, grid.n_cells_x)
    grid.y_cc = np.linspace(grid.dy / 2, grid.Ly - grid.dy / 2, grid.n_cells_y)
    grid.X_cc, grid.Y_cc = np.meshgrid(grid.x_cc, grid.y_cc)
    return grid

def plot_results(u, v, p, grid):
    plt.style.use('default')
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.title('Velocity Streamlines')
    plt.xlabel('x'); plt.ylabel('y')
    velocity_mag = np.sqrt(u**2 + v**2)
    plt.streamplot(grid.X_cc, grid.Y_cc, u, v, density=1.5, color=velocity_mag, cmap='viridis')
    plt.colorbar(label='Velocity Magnitude')
    plt.xlim(0, grid.Lx); plt.ylim(0, grid.Ly)
    plt.gca().set_aspect('equal', adjustable='box')

    plt.subplot(1, 2, 2)
    plt.title('Pressure Contours')
    plt.xlabel('x'); plt.ylabel('y')
    plt.contourf(grid.X_cc, grid.Y_cc, p, levels=50, cmap='viridis')
    plt.colorbar(label='Pressure')
    plt.xlim(0, grid.Lx); plt.ylim(0, grid.Ly)
    plt.gca().set_aspect('equal', adjustable='box')

    plt.tight_layout()
    plt.show()

"""## Cell 3: The `solve` Function (Core Logic)"""

def solve(grid, config):
    # Unpack parameters
    Nx, Ny = grid.Nx, grid.Ny
    n_cells_x, n_cells_y = grid.n_cells_x, grid.n_cells_y
    total_cells = grid.total_cells
    dx, dy = grid.dx, grid.dy
    rho, mu, U_lid = config['physics']['rho'], config['physics']['mu'], config['physics']['U_lid']
    alpha_u, alpha_p = config['solver']['alpha_u'], config['solver']['alpha_p']
    max_iter, tol = config['solver']['max_iter'], config['solver']['tolerance']

    # Initialize fields
    u = np.zeros((n_cells_y, n_cells_x))
    v = np.zeros((n_cells_y, n_cells_x))
    p = np.zeros((n_cells_y, n_cells_x))
    p_prime = np.zeros_like(p)

    for i in range(max_iter):
        # --- Store old values for residual calculation ---
        u_old, v_old = u.copy(), v.copy()

        # --- U-Momentum Predictor ---
        # 1. Convection and Diffusion coefficients (Hybrid Scheme)
        u_e_face = 0.5 * (u[:, :-1] + u[:, 1:])
        v_n_face = 0.5 * (v[:-1, :] + v[1:, :])

        Pe_e = (rho * u_e_face * dx) / mu
        Pe_n = (rho * v_n_face * dy) / mu

        F_e = rho * u_e_face * dy
        F_n = rho * v_n_face * dx
        D_e = mu * dy / dx
        D_n = mu * dx / dy

        a_E_u = D_e - 0.5 * F_e
        a_W_u = D_e + 0.5 * F_e[:, :-1] # Corrected slicing
        a_N_u = D_n - 0.5 * F_n[:-1, :] # Corrected slicing
        a_S_u = D_n + 0.5 * F_n[1:, :] # Corrected slicing

        # 2. Pressure Gradient Source Term
        S_p_u = -(p[:, 1:] - p[:, :-1]) * dy

        # 3. Boundary Conditions
        a_W_u[:, 0] = 0; a_E_u[:, -1] = 0
        a_S_u[0, :] = 0; a_N_u[-1, :] = 0
        a_P_u = a_E_u + a_W_u + a_N_u + a_S_u # Corrected calculation of a_P_u
        a_P_u[0, : ] += D_n # Bottom wall
        a_P_u[-1, :] += D_n; S_p_u[-1, :] += 2 * D_n * U_lid # Top wall (Lid)
        a_P_u[:, 0] += D_e; a_P_u[:, -1] += D_e # Side walls

        # 4. Solve for u_star
        A_u = spdiags([-a_S_u.flatten(), -a_W_u.flatten(), a_P_u.flatten(), a_E_u.flatten(), a_N_u.flatten()],
                      [-n_cells_x, -1, 0, 1, n_cells_x], total_cells, total_cells, format='csr')
        u.flat, _ = bicgstab(A_u, S_p_u.flatten())

        # --- V-Momentum Predictor (similar steps) ---
        a_E_v = D_e[:, :-1] - 0.5 * F_e[:, :-1] # Corrected slicing
        a_W_v = D_e[:, 1:] + 0.5 * F_e[:, 1:] # Corrected slicing
        a_N_v = D_n[:-1, :] - 0.5 * F_n[:-1, :] # Corrected slicing
        a_S_v = D_n[1:, :] + 0.5 * F_n[1:, :] # Corrected slicing

        S_p_v = -(p[1:, :] - p[:-1, :]) * dx
        a_W_v[:, 0] = 0; a_E_v[:, -1] = 0
        a_S_v[0, :] = 0; a_N_v[-1, :] = 0
        a_P_v = a_E_v + a_W_v + a_N_v + a_S_v # Corrected calculation of a_P_v
        a_P_v[0, : ] += D_n; a_P_v[-1, :] += D_n
        a_P_v[:, 0] += D_e; a_P_v[:, -1] += D_e
        A_v = spdiags([-a_S_v.flatten(), -a_W_v.flatten(), a_P_v.flatten(), a_E_v.flatten(), a_N_v.flatten()],
                      [-n_cells_x, -1, 0, 1, n_cells_x], total_cells, total_cells, format='csr')
        v.flat, _ = bicgstab(A_v, S_p_v.flatten())

        # --- Pressure Correction ---
        d_u = dy / a_P_u
        d_v = dx / a_P_v
        a_E_p = rho * d_u[:, :-1] * dy
        a_W_p = rho * d_u[:, 1:] * dy
        a_N_p = rho * d_v[:-1, :] * dx
        a_S_p = rho * d_v[1:, :] * dx
        a_P_p = a_E_p + a_W_p + a_N_p + a_S_p

        b_p_flat = ((rho * (u[:,:-1] - u[:,1:]) * dy) + (rho * (v[:-1,:] - v[1:,:]) * dx)).flatten()
        b_p_flat[0] = 0

        Ap = spdiags([-a_S_p.flatten(), -a_W_p.flatten(), a_P_p.flatten(), a_E_p.flatten(), a_N_p.flatten()],
                     [-n_cells_x, -1, 0, 1, n_cells_x], total_cells, total_cells, format='csr')
        Ap.data[Ap.indptr[0]:Ap.indptr[1]] = 0; Ap[0,0] = 1

        p_prime.flat, _ = cg(Ap, b_p_flat)
        p += alpha_p * p_prime

        # --- Velocity Correction ---
        u[:, 1:-1] += alpha_u * 0.5 * (d_u[:, 1:-1] + d_u[:, :-2]) * (p_prime[:, 1:-1] - p_prime[:, 2:])
        v[1:-1, :] += alpha_u * 0.5 * (d_v[1:-1, :] + d_v[:-2, :]) * (p_prime[1:-1, :] - p_prime[2:, :])

        # --- Check for Convergence ---
        res = np.linalg.norm(u - u_old) + np.linalg.norm(v - v_old)
        print(f"Iter: {i+1:>4} | Residual: {res:<10.3e}")
        if res < tol:
            print("Converged!")
            break

    return u, v, p

"""## Cell 4: Main Execution"""

if __name__ == '__main__':
    grid = create_grid(config['grid'])
    u_final, v_final, p_final = solve(grid, config)
    plot_results(u_final, v_final, p_final, grid)