name: PyFlow CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install (editable)
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest numpy scipy || true
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest -q
