name: PyFlow CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-type:
    name: Lint & Type (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff Lint
        run: ruff check .
      - name: Ruff Format Check
        run: ruff format --check .
      - name: Mypy Type Check
        run: mypy src/pyflow

  test:
    name: Tests (Py ${{ matrix.python }} / ${{ matrix.os }})
    needs: lint-type
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest -q
